repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: uv run poe format
        language: system
        types: [python]
        pass_filenames: false

      - id: check
        name: check
        entry: uv run poe check
        language: system
        types: [python]
        pass_filenames: false
